Sk 25
SeekrLabs/Seekr pull request #14
Opened 2020-02-25 18:41 UTC by jhunnie

Right now, waiting on Russell's code for actual logo url and adding that to the model. Code creates a PNG image and saves a temporary file to whatever local directory you're in. I can create another folder just for these temporary images if necessary. The function that will store the image to S3 and generate the image_url will be needed before I delete the image from local. 

Testing: just some basic local testing with various string lengths to check for any writing overflow.

2020-02-25 20:42 UTC, wangwalton commented on postings/models.py
>          #img = Image.new('RGB', (570, 430), color = (255, 255, 255))
rm

2020-02-25 20:47 UTC, wangwalton commented on postings/models.py
> +        return "%s %s %s" % (self.company, self.title, self.date_posted)
revert

2020-02-25 20:50 UTC, wangwalton commented on postings/models.py
> +        # draw text, Company Title
rm

2020-02-25 20:52 UTC, wangwalton requested changes
Can you upload 3 examples of what the card looks like?

2020-03-20 19:35 UTC, jhunnie commented on postings/models.py
>          #img = Image.new('RGB', (570, 430), color = (255, 255, 255))
done

2020-03-20 19:35 UTC, jhunnie commented on postings/models.py
> +        return "%s %s %s" % (self.company, self.title, self.date_posted)
done

2020-03-25 23:59 UTC, jhunnie commented
![1](https://user-images.githubusercontent.com/14086099/77596698-210ee300-6ed3-11ea-880a-62e45bea176d.png)
![2](https://user-images.githubusercontent.com/14086099/77596700-21a77980-6ed3-11ea-93a1-4b4c2ae5fa56.png)
![3](https://user-images.githubusercontent.com/14086099/77596701-21a77980-6ed3-11ea-8a1b-dadbf645a405.png)

2020-03-27 16:18 UTC, merged